# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class SummaryStatisticsProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessStatistics = channel.unary_unary(
                '/statistics.SummaryStatisticsProcessor/ProcessStatistics',
                request_serializer=api__pb2.ProcessStatisticsRequest.SerializeToString,
                response_deserializer=api__pb2.ProcessStatisticsReply.FromString,
                )


class SummaryStatisticsProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummaryStatisticsProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessStatistics,
                    request_deserializer=api__pb2.ProcessStatisticsRequest.FromString,
                    response_serializer=api__pb2.ProcessStatisticsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistics.SummaryStatisticsProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SummaryStatisticsProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics.SummaryStatisticsProcessor/ProcessStatistics',
            api__pb2.ProcessStatisticsRequest.SerializeToString,
            api__pb2.ProcessStatisticsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
