// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SummaryStatisticsProcessorClient is the client API for SummaryStatisticsProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummaryStatisticsProcessorClient interface {
	ProcessStatistics(ctx context.Context, in *ProcessStatisticsRequest, opts ...grpc.CallOption) (*ProcessStatisticsReply, error)
}

type summaryStatisticsProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewSummaryStatisticsProcessorClient(cc grpc.ClientConnInterface) SummaryStatisticsProcessorClient {
	return &summaryStatisticsProcessorClient{cc}
}

func (c *summaryStatisticsProcessorClient) ProcessStatistics(ctx context.Context, in *ProcessStatisticsRequest, opts ...grpc.CallOption) (*ProcessStatisticsReply, error) {
	out := new(ProcessStatisticsReply)
	err := c.cc.Invoke(ctx, "/statistics.SummaryStatisticsProcessor/ProcessStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummaryStatisticsProcessorServer is the server API for SummaryStatisticsProcessor service.
// All implementations must embed UnimplementedSummaryStatisticsProcessorServer
// for forward compatibility
type SummaryStatisticsProcessorServer interface {
	ProcessStatistics(context.Context, *ProcessStatisticsRequest) (*ProcessStatisticsReply, error)
	mustEmbedUnimplementedSummaryStatisticsProcessorServer()
}

// UnimplementedSummaryStatisticsProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedSummaryStatisticsProcessorServer struct {
}

func (UnimplementedSummaryStatisticsProcessorServer) ProcessStatistics(context.Context, *ProcessStatisticsRequest) (*ProcessStatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessStatistics not implemented")
}
func (UnimplementedSummaryStatisticsProcessorServer) mustEmbedUnimplementedSummaryStatisticsProcessorServer() {
}

// UnsafeSummaryStatisticsProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummaryStatisticsProcessorServer will
// result in compilation errors.
type UnsafeSummaryStatisticsProcessorServer interface {
	mustEmbedUnimplementedSummaryStatisticsProcessorServer()
}

func RegisterSummaryStatisticsProcessorServer(s grpc.ServiceRegistrar, srv SummaryStatisticsProcessorServer) {
	s.RegisterService(&SummaryStatisticsProcessor_ServiceDesc, srv)
}

func _SummaryStatisticsProcessor_ProcessStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummaryStatisticsProcessorServer).ProcessStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statistics.SummaryStatisticsProcessor/ProcessStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummaryStatisticsProcessorServer).ProcessStatistics(ctx, req.(*ProcessStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SummaryStatisticsProcessor_ServiceDesc is the grpc.ServiceDesc for SummaryStatisticsProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SummaryStatisticsProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.SummaryStatisticsProcessor",
	HandlerType: (*SummaryStatisticsProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessStatistics",
			Handler:    _SummaryStatisticsProcessor_ProcessStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
